# Generated by Django 5.2.7 on 2025-11-09 09:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionreservation',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluated_nickname',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluator_nickname',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='room_id',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='is_mood_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='room_app.room'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionreservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreservation',
            unique_together={('session', 'user')},
        ),
        migrations.CreateModel(
            name='RoomAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='room_app.room')),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
                'unique_together': {('room', 'time')},
            },
        ),
        migrations.DeleteModel(
            name='RoomAvailability',
        ),
    ]
