# Generated by Django 5.2.7 on 2026-01-25 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0002_alter_sessionreservation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_group_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
