# Generated by Django 5.2.7 on 2026-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0003_groupchat_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
