"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
from datetime import timedelta  # 이 import를 파일 상단에 추가

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent  # backend/ 상위 폴더 (프로젝트 루트)


# --- 👇 .env 파일을 로드하는 코드 추가 ---
load_dotenv(os.path.join(BASE_DIR, '.env'))
# --- 👆 여기까지 추가 ---

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a1uohg%oa&8k5#&8yghj92gnvtx6bu!#!9@r=3(n%(&^w#0y0j'

# SECURITY WARNING: don't run with debug turned on in production!
# [수정] 보안을 위해 배포 시엔 False (환경변수로 제어 추천)
DEBUG = 'RENDER' not in os.environ

# [수정] 모든 호스트 허용 (Render가 주는 도메인 허용)
ALLOWED_HOSTS = ['*']

# [추가] CSRF 설정 (Render 도메인 신뢰)
CSRF_TRUSTED_ORIGINS = [
    "https://bandicon-change3.onrender.com",
    "https://bandicon-test.onrender.com",
    "http://localhost:3000",
    ]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- 👇 여기에 추가 ---
    'rest_framework',             # Django Rest Framework
    'rest_framework_simplejwt',   # Simple JWT
    'corsheaders',              # CORS 헤더

    # --- 우리가 만든 앱 ---
    'user_app',
    'room_app',     # <-- 추가
    'board_app',    # <-- 추가
    'clan_app',     # <-- 추가
    'support_app',  # <-- 추가                   # User 관련 앱
    # (나중에 'room_app', 'board_app' 등을 여기에 추가할 것입니다)
    # --- 👆 여기까지 추가 ---
]

MIDDLEWARE = [
    # --- 👇 여기에 추가 ---
    'corsheaders.middleware.CorsMiddleware',
    # --- 👆 여기까지 추가 ---
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # 👈 여기 추가
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(ROOT_DIR, 'frontend', 'build'), # React 빌드 결과물 (index.html) 위치
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# [수정] WSGI 대신 ASGI를 사용하도록 설정
WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# [추가] 채널 레이어 설정 (개발용: In-Memory)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- 👇 기존 DATABASES 설정을 이 내용으로 덮어쓰세요 ---
#DATABASE_URL = os.getenv("DATABASE_URL")
#if DATABASE_URL and DATABASE_URL.startswith("postgres://"):
#    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+psycopg2://", 1)

#if DATABASE_URL:
#    DATABASES = {
#        'default': dj_database_url.parse(DATABASE_URL)
#    }
#else:
    # .env 파일에 DATABASE_URL이 없을 경우를 대비한 로컬 설정

# [수정] DB 설정 (Render PostgreSQL 자동 연결)
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}
# --- 👆 여기까지 덮어쓰기 ---

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# [수정] 정적 파일 설정
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# React 정적 파일 경로 추가
STATICFILES_DIRS = [
    os.path.join(ROOT_DIR, 'frontend', 'build', 'static'),
]

# --- 👇 React 연동을 위한 CORS 설정 ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://bandicon-change3.onrender.com",
    # (추후 React 개발 서버 주소가 다르거나,
    #  실제 배포 주소가 있다면 여기에 추가)
]
CORS_ALLOW_CREDENTIALS = True # (선택) 쿠키/인증 헤더를 허용
# --- 👆 여기까지 추가 ---
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- 👇 우리가 만든 User 모델을 Django의 기본 유저 모델로 지정 ---
AUTH_USER_MODEL = 'user_app.User'
# --- 👆 여기까지 추가 ---

# config/settings.py

# ... (파일 맨 아래, AUTH_USER_MODEL 설정 다음) ...

# --- 👇 Django Rest Framework 및 JWT 설정 ---
# [수정] Redis 설정 (Render Redis 자동 연결)
if 'REDIS_URL' in os.environ:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get('REDIS_URL')],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # React가 'Bearer <token>' 헤더를 보내면 이 클래스가 인증을 처리
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # 기본적으로는 인증된 사용자만 접근 허용
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# simple-jwt가 username 필드 (즉, FastAPI의 'id')를 사용하도록 설정
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 액세스 토큰 유효기간 60분
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 리프레시 토큰 유효기간 7일
    'ROTATE_REFRESH_TOKENS': True,                   # 리프레시 토큰 재발급 시 새 토큰 생성
    'BLACKLIST_AFTER_ROTATION': False,               # 기존 리프레시 토큰 블랙리스트 처리 (일단 False)
    'UPDATE_LAST_LOGIN': True,                       # 로그인 시 last_login 필드 업데이트
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),                # Authorization: Bearer <token>
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',                          # 토큰 페이로드의 user_id
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}
# --- 👆 여기까지 추가 ---

# --- 👇 파일 업로드 (Media) 설정 ---

# React가 /media/ URL로 파일에 접근
MEDIA_URL = '/media/'

# 파일이 실제로 저장될 서버의 폴더 경로
# (BASE_DIR은 'manage.py'가 있는 폴더입니다)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# --- 👆 여기까지 추가 ---

# 추가로 CORS 관련 설정
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


DEBUG = True



APPEND_SLASH = True