# Generated by Django 5.2.7 on 2025-11-09 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanchat',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='clanboard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clanboard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clanchat',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='clanevent',
            name='attendees',
        ),
        migrations.AddField(
            model_name='clan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clan_images/'),
        ),
        migrations.AddField(
            model_name='clanannouncement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clanannouncement',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clanboard',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clanboard',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('info', '정보'), ('music', '음악')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='clanboard',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clanboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clanboard',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clanevent',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clanevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clanjoinrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clan',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clanannouncement',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clanannouncement',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clanchat',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clanchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clanchat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clanevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clanevent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clanevent',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clanjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='clanjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clanjoinrequest',
            unique_together={('clan', 'user')},
        ),
        migrations.DeleteModel(
            name='ClanLedger',
        ),
    ]
