# Generated by Django 5.2.7 on 2025-11-16 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0002_alter_clanchat_options_remove_clanboard_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_clans', to=settings.AUTH_USER_MODEL),
        ),
    ]
