# Generated by Django 5.2.7 on 2025-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0003_clan_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('active', '활성'), ('rejected', '거절')], default='pending', max_length=10),
        ),
    ]
