# Generated by Django 5.2.7 on 2026-01-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0004_clan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
