# Generated by Django 5.2.7 on 2026-01-25 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0005_clan_youtube_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clanchat',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_clan_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
