# Generated by Django 5.2.7 on 2025-11-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
