# Generated by Django 5.2.7 on 2026-01-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0003_delete_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='관리자용 식별 제목', max_length=100)),
                ('image', models.ImageField(help_text='배너 이미지 (권장 크기: 393x230)', upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='배너 클릭 시 이동할 URL (선택)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
