# Generated by Django 5.2.7 on 2025-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', '멤버'), ('MANAGER', '간부'), ('ADMIN', '운영자')], default='MEMBER', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절')], default='approved', max_length=20),
        ),
    ]
