# Generated by Django 5.2.7 on 2025-11-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
    ]
