# Generated by Django 5.2.7 on 2025-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_marketing_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', '사용자'), ('OPERATOR', '운영자')], default='USER', max_length=50),
        ),
    ]
