# Generated by Django 5.2.7 on 2026-01-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
